### ISSUE TITLE
choreonoid最新版への対応

### ISSUE THREAD

**Issue by fkanehiro** [jvrc/JVRCPlugin#5]
choreonoidの最新版ではSceneVisitorがなくなりコンパイルできなくなっています。
名前が変わったとかそういう単純な変更ではなさそうなので、最新版への対応方法を教えて頂くか、最新版への対応をお願いできませんか？@s-nakaoka さん。

**Comment by s-nakaoka** [comment]
すみません、こちらの対応を忘れていました。対応しますのでしばらくお待ち下さい。

**Comment by s-nakaoka** [comment]
コンパイルできるよう修正しました。

**Comment by fkanehiro** [comment]
ありがとうございます。
